export const AGENT_REQUEST_MAX_BYTES = 4 * 1024 * 1024;
export const AGENT_MAX_CONCURRENT_REQUESTS = 4;
export const EXTRACTION_CONCURRENCY = 2;
export const MATERIAL_PROCESSING_MAX_MS = 5 * 60_000;
export const MODEL_PROCESSING_MAX_MS = 3 * 60_000;
