import { MAX_DIAGNOSTIC_NODES } from "./knowledge-map-limits";

export const REPORT_AGENT_NODE_LIMIT = 40;
export const REPORT_AGENT_SUMMARY_CHARACTER_LIMIT = 2_000;
export const MAX_REPORT_SUMMARY_CHARACTERS =
  MAX_DIAGNOSTIC_NODES * REPORT_AGENT_SUMMARY_CHARACTER_LIMIT;

// 保留报告长度硬边界，同时容纳每个主题的证据、来源和 Markdown 结构。
export const MAX_REPORT_MARKDOWN_CHARACTERS =
  MAX_REPORT_SUMMARY_CHARACTERS + MAX_DIAGNOSTIC_NODES * 20_000;
